apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: webapp-staging

configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html

labels:
  - pairs:
      environment: staging
    includeSelectors: false

replicas:
  - name: webapp
    count: 2
