apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: webapp-prod

configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html

labels:
  - pairs:
      environment: prod
    includeSelectors: false

replicas:
  - name: webapp
    count: 3

images:
  - name: nginx
    newTag: 1.27.4-alpine

patches:
  - path: patch-resources.yaml
