apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: webapp-qa

configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html

labels:
  - pairs:
      environment: qa
    includeSelectors: false

replicas:
  - name: webapp
    count: 2

patches:
  - path: patch-annotation.yaml
    target:
      kind: Deployment
      name: webapp
