apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: web-content
    files:
      - index.html

labels:
  - pairs:
      app.kubernetes.io/name: webapp
    includeSelectors: true
